  const projectCreatePopup = () => {
    let container = document.createElement("div");
    container.classList.add("popup");
    let title = document.createElement("input");
    title.setAttribute("id","projecttitle");
    title.type = "text";
    let submit = document.createElement("button");
    submit.setAttribute("id","addprojectbutton");
    submit.innerHTML = "Submit";
    let close = document.createElement("button");
    close.setAttribute("id","close");
    close.innerHTML = "Close";
    let label = document.createElement("label");
    label.innerHTML = "Title: ";
    let heading = document.createElement("p");
    heading.classList.add("popup-header");
    heading.innerHTML = "Create Project";
    container.appendChild(heading);
    container.appendChild(label);
    container.appendChild(title);
    container.appendChild(submit);
    container.appendChild(close);
    container.setAttribute("id","projectcreatepopup")
    let body = document.getElementById("body");
    let cont = document.getElementById("container");
    body.insertBefore(container,cont);
  };

  const todoCreatePopup = () => {
    let container = document.createElement("div");
    container.classList.add("popup");
    let title = document.createElement("input");
    title.setAttribute("id","todotitle");
    title.type = "text";
    let titlelabel = document.createElement("label");
    titlelabel.setAttribute("id","titlelabel");
    titlelabel.innerHTML = "Title: ";
    let description = document.createElement("input");
    description.setAttribute("id","tododescription");
    description.type = "text";
    let descriptionlabel = document.createElement("label");
    descriptionlabel.setAttribute("id","descriptionlabel");
    descriptionlabel.innerHTML = "Description: ";
    let duedate = document.createElement("input");
    duedate.setAttribute("id","tododuedate");
    duedate.type = "date";
    let duedatelabel = document.createElement("label");
    duedatelabel.setAttribute("id","duedatelabel");
    duedatelabel.innerHTML = "Duedate: ";
    let prioritylabel = document.createElement("label");
    prioritylabel.setAttribute("id","prioritylabel");
    prioritylabel.innerHTML = "Priority(1-10): ";
    let priority = document.createElement("input");
    priority.setAttribute("id","todopriority");
    priority.type = "number";
    let notes = document.createElement("input");
    notes.setAttribute("id","todonotes");
    notes.type = "text";
    let noteslabel = document.createElement("label");
    noteslabel.setAttribute("id","noteslabel");
    noteslabel.innerHTML = "Notes: ";
    let submit = document.createElement("button");
    submit.innerHTML = "Submit";
    submit.setAttribute("id","addtodobutton");
    let close = document.createElement("button");
    close.setAttribute("id","close");
    close.innerHTML = "Close";
    let heading = document.createElement("p");
    heading.classList.add("popup-header");
    heading.innerHTML = "Create Todo";
    container.appendChild(heading);
    container.appendChild(titlelabel);
    container.appendChild(title);
    container.appendChild(document.createElement("br"));
    container.appendChild(descriptionlabel);
    container.appendChild(description);
    container.appendChild(document.createElement("br"));
    container.appendChild(duedatelabel);
    container.appendChild(duedate);
    container.appendChild(document.createElement("br"));
    container.appendChild(prioritylabel);
    container.appendChild(priority);
    container.appendChild(document.createElement("br"));
    container.appendChild(noteslabel);
    container.appendChild(notes);
    container.appendChild(document.createElement("br"));
    container.appendChild(submit);
    container.appendChild(close);
    container.setAttribute("id","todocreatepopup");
    let body = document.getElementById("body");
    let cont = document.getElementById("container");
    body.insertBefore(container,cont);
  }

  const createTodoInfoView = (todo) => {
    let container = document.createElement("div");
    let heading = returnTodoEle("Todo","info-header");
    let title = returnTodoEle("Title: " + todo.title,"todoinfoele");
    let description = returnTodoEle("Description: " + todo.description,"todoinfoele");
    let duedate = returnTodoEle("Duedate: " + todo.duedate,"todoinfoele");
    let priority = returnTodoEle("Priority: " + todo.priority,"todoinfoele");
    let notes = returnTodoEle("Notes: " + todo.notes,"todoinfoele");
    let deleteButton = document.createElement("button");
    deleteButton.classList.add("button");
    deleteButton.innerHTML = "Delete Todo";
    deleteButton.setAttribute("id","deletetodobutton");
    let editButton = document.createElement("button");
    editButton.classList.add("button");
    editButton.innerHTML = "Edit Todo";
    editButton.setAttribute("id","edittodobutton");
    container.appendChild(heading);
    container.appendChild(title);
    container.appendChild(description);
    container.appendChild(duedate);
    container.appendChild(priority);
    container.appendChild(notes);
    container.appendChild(deleteButton);
    container.appendChild(editButton);
    container.setAttribute("id","todoinfocontainer");
    return container;
  }

  const returnTodoEle = (text,classadd) => {
    let ele = document.createElement("p");
    ele.classList.add(classadd);
    ele.innerHTML = text;
    return ele;
  }

  const projectEditPopup = (theProject) => {
    let container = document.createElement("div");
    container.classList.add("popup");
    let title = document.createElement("input");
    title.setAttribute("id","projecttitle");
    title.type = "text";
    let submit = document.createElement("button");
    submit.setAttribute("id","editprojectbutton");
    submit.setAttribute("data-attr",theProject.title);
    submit.innerHTML = "Submit";
    let close = document.createElement("button");
    close.setAttribute("id","close");
    close.innerHTML = "Close";
    let label = document.createElement("label");
    label.innerHTML = "Title: ";
    let heading = document.createElement("p");
    heading.classList.add("popup-header");
    heading.innerHTML = "Edit Project";
    container.appendChild(heading);
    container.appendChild(label);
    container.appendChild(title);
    container.appendChild(submit);
    container.appendChild(close);
    container.setAttribute("id","projecteditpopup")
    let body = document.getElementById("body");
    let cont = document.getElementById("container");
    body.insertBefore(container,cont);
  }

  const todoEditPopup = (theProject,theTodo) => {
    let container = document.createElement("div");
    container.classList.add("popup");
    let title = document.createElement("input");
    title.setAttribute("id","todotitle");
    title.type = "text";
    let titlelabel = document.createElement("label");
    titlelabel.setAttribute("id","titlelabel");
    titlelabel.innerHTML = "Title: ";
    let description = document.createElement("input");
    description.setAttribute("id","tododescription");
    description.type = "text";
    let descriptionlabel = document.createElement("label");
    descriptionlabel.setAttribute("id","descriptionlabel");
    descriptionlabel.innerHTML = "Description: ";
    let duedate = document.createElement("input");
    duedate.setAttribute("id","tododuedate");
    duedate.type = "date";
    let duedatelabel = document.createElement("label");
    duedatelabel.setAttribute("id","duedatelabel");
    duedatelabel.innerHTML = "Duedate: ";
    let prioritylabel = document.createElement("label");
    prioritylabel.setAttribute("id","prioritylabel");
    prioritylabel.innerHTML = "Priority(1-10): ";
    let priority = document.createElement("input");
    priority.setAttribute("id","todopriority");
    priority.type = "number";
    let notes = document.createElement("input");
    notes.setAttribute("id","todonotes");
    notes.type = "text";
    let noteslabel = document.createElement("label");
    noteslabel.setAttribute("id","noteslabel");
    noteslabel.innerHTML = "Notes: ";
    let submit = document.createElement("button");
    submit.innerHTML = "Submit";
    submit.setAttribute("id","edittodobutton");
    submit.setAttribute("todo-hash",theTodo.hash);
    submit.setAttribute("project",theProject.title);
    let close = document.createElement("button");
    close.setAttribute("id","close");
    close.innerHTML = "Close";
    let heading = document.createElement("p");
    heading.classList.add("popup-header");
    heading.innerHTML = "Edit Todo";
    container.appendChild(heading);
    container.appendChild(titlelabel);
    container.appendChild(title);
    container.appendChild(document.createElement("br"));
    container.appendChild(descriptionlabel);
    container.appendChild(description);
    container.appendChild(document.createElement("br"));
    container.appendChild(duedatelabel);
    container.appendChild(duedate);
    container.appendChild(document.createElement("br"));
    container.appendChild(prioritylabel);
    container.appendChild(priority);
    container.appendChild(document.createElement("br"));
    container.appendChild(noteslabel);
    container.appendChild(notes);
    container.appendChild(document.createElement("br"));
    container.appendChild(submit);
    container.appendChild(close);
    container.setAttribute("id","todoeditpopup");
    let body = document.getElementById("body");
    let cont = document.getElementById("container");
    body.insertBefore(container,cont);
  }
export {projectCreatePopup,todoCreatePopup,createTodoInfoView,projectEditPopup,todoEditPopup};
